fix(#425): Removing reference by id that returns boolean result ends with exception
Method with signature:

```java
/**
     * Removes the tag reference if it exists.
     * @param tagId tag id to be removed
     * @return true if the tag was removed, false if it did not exist
     */
    @ReferenceRef(WithPublishedTags.REFERENCE_TAG)
    @RemoveWhenExists
    boolean removeTagById(int tagId);
```

Throws exception when invoked:

```
ERROR Failed to index entity eG_cym-group in catalog milagro_cz due to: Failed to wrap `SealedEntity` into class `boolean` due to: Failed to wrap `SealedEntity` into class `boolean` due to: Cannot find any constructor with matching arguments in class: `boolean`
io.evitadb.api.exception.EntityClassInvalidException: Failed to wrap `SealedEntity` into class `boolean` due to: Failed to wrap `SealedEntity` into class `boolean` due to: Cannot find any constructor with matching arguments in class: `boolean`
	at io.evitadb.api.proxy.impl.ProxycianFactory.createReferenceProxy(ProxycianFactory.java:344) ~[evita_api-10.2.0.jar:?]
	at io.evitadb.api.proxy.impl.ProxycianFactory.createEntityReferenceProxy(ProxycianFactory.java:186) ~[evita_api-10.2.0.jar:?]
	at io.evitadb.api.proxy.impl.AbstractEntityProxyState.lambda$getOrCreateEntityReferenceProxy$7(AbstractEntityProxyState.java:401) ~[evita_api-10.2.0.jar:?]
	at io.evitadb.api.proxy.impl.AbstractEntityProxyState.lambda$getOrCreateEntityReferenceProxy$8(AbstractEntityProxyState.java:410) ~[evita_api-10.2.0.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at io.evitadb.api.proxy.impl.AbstractEntityProxyState.getOrCreateEntityReferenceProxy(AbstractEntityProxyState.java:408) ~[evita_api-10.2.0.jar:?]
	at io.evitadb.api.proxy.impl.SealedEntityProxyState.getOrCreateEntityReferenceProxy(SealedEntityProxyState.java:67) ~[evita_api-10.2.0.jar:?]
	at io.evitadb.api.proxy.impl.entityBuilder.SetReferenceMethodClassifier.lambda$removeReferencedEntityIdWithReferenceResult$55(SetReferenceMethodClassifier.java:1606) ~[evita_api-10.2.0.jar:?]
	at one.edee.oss.proxycian.bytebuddy.ByteBuddyDispatcherInvocationHandler.interceptMethodCall(ByteBuddyDispatcherInvocationHandler.java:94) ~[proxycian_bytebuddy-1.3.10.jar:?]
	at one.edee.oss.proxycian.bytebuddy.ByteBuddyDispatcherInvocationHandler.interceptMethodCall(ByteBuddyDispatcherInvocationHandler.java:46) ~[proxycian_bytebuddy-1.3.10.jar:?]
	at one.edee.oss.proxycian.bytebuddy.generated.PublishedGroupEditor_365.removeTagById(Unknown Source) ~[proxycian_bytebuddy-1.3.10.jar:?]
```